# [\#17 Issue](https://github.com/mattduck/gh2md/issues/17) `closed`: UnicodeEncodeError: 'ascii' codec can't encode character

#### <img src="https://avatars.githubusercontent.com/u/7646335?u=aca4d581478f7a156c062e36130b55a776476727&v=4" width="50">[akiicat](https://github.com/akiicat) opened issue at [2020-12-31 08:18](https://github.com/mattduck/gh2md/issues/17):

**error log**

```
Traceback (most recent call last):
  File "/home/akiicat/.local/lib/python2.7/site-packages/gh2md/gh2md.py", line 196, in export_issues_to_markdown_file
    formatted_issue = process_issue_to_markdown(issue)
  File "/home/akiicat/.local/lib/python2.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/akiicat/.local/lib/python2.7/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/home/akiicat/.local/lib/python2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/akiicat/.local/lib/python2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/akiicat/.local/lib/python2.7/site-packages/gh2md/gh2md.py", line 249, in process_issue_to_markdown
    body=comment.body,
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 173: ordinal not in range(128)
Couldn't process issue due to exceptions, skipping
```

It seems the string in [templates_markdown.py](https://github.com/mattduck/gh2md/blob/master/src/gh2md/templates_markdown.py#L18) file are not Unicode strings. One of my solutions is:

```diff
# src/gh2md/templates_markdown.py
- COMMENT = r"""#### <img src="{avatar_url}" width="50">[{author}]({author_url}) commented at [{date}]({url}):
+ COMMENT = ur"""#### <img src="{avatar_url}" width="50">[{author}]({author_url}) commented at [{date}]({url}):
```


#### <img src="https://avatars.githubusercontent.com/u/1607892?u=196bf09c14472eee8dccaaecbef3c16974c8e69f&v=4" width="50">[mattduck](https://github.com/mattduck) commented at [2021-01-03 19:27](https://github.com/mattduck/gh2md/issues/17#issuecomment-753664999):

@akiicat thanks for reporting this. I'm hoping to release a version with the fix sometime this week.

#### <img src="https://avatars.githubusercontent.com/u/1607892?u=196bf09c14472eee8dccaaecbef3c16974c8e69f&v=4" width="50">[mattduck](https://github.com/mattduck) commented at [2021-03-14 20:45](https://github.com/mattduck/gh2md/issues/17#issuecomment-798976684):

@akiicat I looked into this and had missed that you're running python 2.7. I wasn't able to reproduce the issue in the latest version. I'm going to close this but I'm happy to look at it if you can reproduce in python 3.


-------------------------------------------------------------------------------



[Export of Github issue for [mattduck/gh2md](https://github.com/mattduck/gh2md). Generated on 2022.08.23 at 12:38:24.]
